### ISSUE TITLE
Question about syntax highlighting and files

### ISSUE THREAD

**Issue by ajloveslily14** [FPtje/SublimeLinter-contrib-glualint#3]
Is there a way to not have this work for every lua file? I program in other lua variants and having the gmod functions pop up can be annoying...

**Comment by FPtje** [comment]
I'm not sure how glualint would be able to see the difference between a GLua file and a normal Lua file. You can probably still use the linter for regular Lua if you disable GMod specific things in the [`glualint.json`](https://github.com/FPtje/GLuaFixer#configuring-glualint) file. Specifically, setting `lint_deprecated` and `prettyprint_cStyle` to `false` *should* make the linter applicable to general Lua. Exceptions are maybe different versions of Lua. Also, glualint will permit syntax that is valid in GLua, but not in general Lua. Things like `continue` and C-style comments and operators. That shouldn't be too much of a problem though.

Alternatively you can turn glualint off by setting everything to false in the `glualint.json` file.
