### ISSUE TITLE
Auto indent triggers trailing whitespace

### ISSUE THREAD

**Issue by shadow7483147** [FPtje/SublimeLinter-contrib-glualint#7]
Yeah, the logical answer is to just disable the trailing whitespace check, but will there be an option to check the indentation level of the next line of written code after a scope declaration (function, condition, etc) and check that against the next lines for indent level consistency until the scope ends?
It's annoying that every vertical whitespace I use triggers trailing whitespace because of auto indent.

**Comment by FPtje** [comment]
The point of that warning is that you should enable the "trim trailing whitespace on save" option of your editor. That way, the indents on empty lines automatically get removed upon saving. Sublime can deal with scopes and trimming trailing whitespace very well iirc
